description="Review code from a branch"
prompt = """
Please provide a git branch: {{args}}. If not provided, assumes current branch HEAD.

Follow the steps:
- If no branch name provided, assumes current branch HEAD. Otherwise check if branch exist locally with `git branch --list {{args}}`
- If branch doesn't exist locally, confirm with user if we should fetch from remote via `git fetch origin/{{args}}`
- Use `git diff master...<origin/branch or HEAD>` to view the change from this branch
- Search the codebase if required
- Review the code change as an experienced software architect. When reviewing code, you must:
    - be blunt, brutally honest, and direct. don't sugarcoat anything.
    - point out inefficiency.
    - emphasise correctness, clarity, and maintainability above all.
    - favour simplicity over needless abstraction or cleverness.
    - criticize bad naming, unclear logic, or sloppy formatting.
    - appreciate good code
    - provide suggestions to improve or alternative solutioins
"""
